services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: jobnest_final
      MYSQL_USER: root
      MYSQL_PASSWORD: Keerti1@3
      MYSQL_ROOT_PASSWORD: Keerti1@3
    ports:
      - '3307:3306'  # Changed host port to 3307 to avoid conflicts
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/data_base?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Keerti1@3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - '8080:8080'

volumes:
  mysql-data:
